/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LkgRouteImport } from './routes/lkg'
import { Route as PreKgRouteImport } from './routes/pre-kg'
import { Route as UkgRouteImport } from './routes/ukg'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LkgRoute = LkgRouteImport.update({
  id: '/lkg',
  path: '/lkg',
  getParentRoute: () => rootRouteImport,
} as any)
const PreKgRoute = PreKgRouteImport.update({
  id: '/pre-kg',
  path: '/pre-kg',
  getParentRoute: () => rootRouteImport,
} as any)
const UkgRoute = UkgRouteImport.update({
  id: '/ukg',
  path: '/ukg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lkg': typeof LkgRoute
  '/pre-kg': typeof PreKgRoute
  '/ukg': typeof UkgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lkg': typeof LkgRoute
  '/pre-kg': typeof PreKgRoute
  '/ukg': typeof UkgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lkg': typeof LkgRoute
  '/pre-kg': typeof PreKgRoute
  '/ukg': typeof UkgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lkg' | '/pre-kg' | '/ukg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lkg' | '/pre-kg' | '/ukg'
  id: '__root__' | '/' | '/lkg' | '/pre-kg' | '/ukg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LkgRoute: typeof LkgRoute
  PreKgRoute: typeof PreKgRoute
  UkgRoute: typeof UkgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lkg': {
      id: '/lkg'
      path: '/lkg'
      fullPath: '/lkg'
      preLoaderRoute: typeof LkgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-kg': {
      id: '/pre-kg'
      path: '/pre-kg'
      fullPath: '/pre-kg'
      preLoaderRoute: typeof PreKgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukg': {
      id: '/ukg'
      path: '/ukg'
      fullPath: '/ukg'
      preLoaderRoute: typeof UkgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LkgRoute: LkgRoute,
  PreKgRoute: PreKgRoute,
  UkgRoute: UkgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
